; PlatformIO Project Configuration File for XIAO ESP32-S3
[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino

; Serial Monitor Speed - set to 115200 baud
monitor_speed = 115200

lib_deps = ;